#!/bin/bash
export HOME=/home/cointhink
cd
echo I am `id` in `pwd`
URL="http://dockerhost:3002/$cointhink_user_name/$cointhink_script_name/$cointhink_script_key"
echo `date` Loading $cointhink_user_name/$cointhink_script_name
wget --quiet -O "$cointhink_script_name" $URL
#echo npm install...
#npm install
echo starting $cointhink_script_name ...
node "$cointhink_script_name"
